// Code generated by protoc-gen-go.
// source: ob_metrics.proto
// DO NOT EDIT!

/*
Package prometheusproxy is a generated protocol buffer package.

It is generated from these files:
	ob_metrics.proto

It has these top-level messages:
	MetricsEnvelope
*/
package prometheusproxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import io_prometheus_client "github.com/prometheus/client_model/go"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MetricsEnvelope struct {
	Owner            *string                            `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
	MetricFamily     *io_prometheus_client.MetricFamily `protobuf:"bytes,2,req,name=metricFamily" json:"metricFamily,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *MetricsEnvelope) Reset()                    { *m = MetricsEnvelope{} }
func (m *MetricsEnvelope) String() string            { return proto.CompactTextString(m) }
func (*MetricsEnvelope) ProtoMessage()               {}
func (*MetricsEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MetricsEnvelope) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

func (m *MetricsEnvelope) GetMetricFamily() *io_prometheus_client.MetricFamily {
	if m != nil {
		return m.MetricFamily
	}
	return nil
}

func init() {
	proto.RegisterType((*MetricsEnvelope)(nil), "prometheusproxy.MetricsEnvelope")
}

func init() { proto.RegisterFile("ob_metrics.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x4f, 0x8a, 0xcf,
	0x4d, 0x2d, 0x29, 0xca, 0x4c, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x07, 0x52,
	0x40, 0x91, 0x8c, 0xd4, 0xd2, 0x62, 0x20, 0xab, 0xa2, 0x52, 0x8a, 0x17, 0x45, 0x5e, 0x29, 0x8a,
	0x8b, 0xdf, 0x17, 0x22, 0xe0, 0x9a, 0x57, 0x96, 0x9a, 0x93, 0x5f, 0x90, 0x2a, 0xc4, 0xcb, 0xc5,
	0x9a, 0x5f, 0x9e, 0x97, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa4, 0xc1, 0x29, 0x64, 0xc1, 0xc5, 0x03,
	0xd1, 0xe2, 0x96, 0x98, 0x9b, 0x99, 0x53, 0x29, 0xc1, 0x04, 0x14, 0xe5, 0x36, 0x52, 0xd2, 0xcb,
	0xcc, 0xd7, 0x43, 0x98, 0xad, 0x97, 0x9c, 0x93, 0x99, 0x9a, 0x57, 0xa2, 0xe7, 0x8b, 0xa4, 0x12,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xe2, 0xf5, 0xef, 0x8e, 0x00, 0x00, 0x00,
}
